"""
Django settings for metin2 project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'asd65496a5sdas6546468a4sd/2%1212qwdas'

# SECURITY WARNING: don't run with debug turned on in production!
#Descomentar para Pruebas
#DEBUG = True

#Descomentar para Produccion
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #se desabilita el capcha para testing.
    #'captcha',
    'bootstrapform',
    'django_markdown',
    'apps.varios',
    'apps.account',
    'apps.player',
    'apps.blog',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'metin2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'metin2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_metin2',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '3306',        
    },
    'player': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'player',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '3306',  
        'OPTIONS': {'charset': 'utf8mb4'},
        #'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",},        
    },
    'account': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'account',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '3306',
        'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'" ,}
    },
    
}

"""Router base de datos para las aplicaciones  """
DATABASE_ROUTERS = {
                    'apps.player.router.playerRouter',
                    'apps.account.router.AccountRouter',
                    }
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

#aqui va el lenguaje seleccionado
LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


STATIC_ROOT = '/root/metin2/static'

"""Aqui van las claves del captcha de google.
las claves se generan en este sitio https://www.google.com/recaptcha/ """

RECAPTCHA_PUBLIC_KEY = ''
RECAPTCHA_PRIVATE_KEY = ''

#Poner en True despues de generar las llaves del recaptcha de google.
NOCAPTCHA = True

#Estos datos son de ejemplo
#por favor descomentar para el envio de correos.
#EMAIL_USE_TLS = True 
#EMAIL_HOST = 'smtp.tudominio.com'
#EMAIL_PORT = 587
#EMAIL_HOST_USER = 'tu-usuario@tudominio.com' 
#EMAIL_HOST_PASSWORD = 'password'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'